"""Update schema untuk Sprint 2 items

Revision ID: 9b26892a2d29
Revises: 42a776b5fd53
Create Date: 2026-04-10 17:10:53.904279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b26892a2d29'
down_revision: Union[str, Sequence[str], None] = '42a776b5fd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
